apiVersion: batch/v1
kind: CronJob
metadata:
  name: wait
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wait
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            args: ['http://webapp:3000/wait/10']
          restartPolicy: OnFailure
